name: Commit CI

on:
  push:
    branches:
      - '*'         # This will match all branches
      - '!main'     # Then exclude main
    tags:
      - '![0-9]+.*'
  pull_request:


jobs:
  lint:
    runs-on: macos-14
    steps:

      - name: Checkout last commit
        uses: actions/checkout@v4

      - name: Checkout submodules/dependencies
        run: bash ./action-install.sh

      - name: Configure build environment
        run: brew update && brew install cmake llvm clang-format nodejs

      - name: Code format lint
        run: bash ./tools/clang-format.sh lint

      - name: Code style lint on modified files
        run: bash ./tools/clang-tidy.sh modified

      - name: Check rime.d.ts
        run: (cd ./tools; node ./check-api-coverage.js)
